apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: ${{ values.projectName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    requests.cpu: "${{ values.quotaRequestsCpu }}"
    requests.memory: "${{ values.quotaRequestsMemory }}"
    limits.cpu: "${{ values.quotaLimitsCpu }}"
    limits.memory: "${{ values.quotaLimitsMemory }}"
    pods: "${{ values.quotaPods }}"
